### ISSUE TITLE
Supporting bundles

### ISSUE THREAD

**Issue by guybedford** [capaj/systemjs-hot-reloader#16]
I just wanted to check if bundle loading is supported alongside this hot reloading? It can be a good way of getting the first page load time down, which then combined with subsequent hot reloading would likely be the ideal development workflow.

**Comment by capaj** [comment]
@guybedford yes, the famous unicorn! 

> bundle loading

I imagine you mean support for building a bundle out of all your dependencies. That way you can build your app and reload only your code, the bundle can stay cached in the browser. Have  I got that right @guybedford ?

**Comment by guybedford** [comment]
Haha, indeed, well ideal at least for jspm to match webpack for development experience :)

I mean like running `jspm bundle app -i`, so that the initial page load is from a single script load, then have hot reloading work for individual modules within the `app` tree, despite it having been loaded via a bundle initially.

**Comment by capaj** [comment]
@guybedford that sounds like the best solution. I have tried to speed up initial load with http2 static server last week, but abandoned that because it is too complicated to run socket.io on SSL.

So  after loading the whole app, if I delete the System.bundles, would that load the modules directly from files next time I call System.import?

**Comment by guybedford** [comment]
Yes exactly it should. Perhaps only delete the bundles that contain the given module's normalized name within their module array to still allow dynamic bundles to work.

**Comment by capaj** [comment]
@guybedford not sure where would I find their `module array`?
I was planning on deteting everything which doesn't have `jspm_packages` in it's path in bundles.

**Comment by capaj** [comment]
@guybedford also by dynamic bundles you are reffering to bundles imported with System.import()?

**Comment by guybedford** [comment]
I mean something along the lines of `if (bundles[bundleName].includes(normalizedNameOfModule)) delete bundles[bundleName]`. Yes exactly, lazy loaded modules after the initial load.

**Comment by peteruithoven** [comment]
While it would be great to lower the initial page load, this would also require rebuilding the bundle after changes right? Otherwise you'll load an old version after a manual refresh. @guybedford I'm curious how you're planning to do that. Using gulp? Combining bundling functionality with [chokidar-socket-emitter](https://github.com/capaj/chokidar-socket-emitter)? 

We have been using this module in combination with bundling just the dependencies, that also helps with the initial page load. 
```
jspm bundle 'js/**/* - [js/**/*]' bundle.js --inject
```

**Comment by capaj** [comment]
@peteruithoven I am planning on doing it basically this way:

1.bundle the whole app into one file
2. in the browser, when a change occurs, delete module AND the bundle from System.bundle so any System.import loads a files from sources, not from bundle

3. we can even track the number of files we're fetching (not from bundle because we have deleted them) and if that starts to grow too much, rebundle in the background and inject the bundle

**Comment by peteruithoven** [comment]
> 1.bundle the whole app into one file by using the main entry file

But what would do that and when? You'd need to do have a bundle ready before the first page load and for every refresh? Would the hot reloader request a fresh bundle on these events? And would a server respond to that by rebundling? 

> and if that starts to grow too much, rebundle in the background and inject the bundle 

Wouldn't that break hot reloading?

**Comment by guybedford** [comment]
Yes, knowing what to bundle initially would require some sort of argument, the issue then is that if there are multiple bundles how to handle that from a workflow perspective. It may end up best to keep the workflows separate from an architectural point of view, but ease-of-use is important too, so I don't know to be honest.

If this was in jspm core (one can dream), the following commands would be pretty cool:

```
# jspm-hot-reloader in core!
jspm serve --port 1234
jspm server started at port 1234, hot reloading enabled

# incremental rebuilds in core!
jspm bundle -i app --watch
build.js built and injected, watching for incremental rebuilds
```

**Comment by peteruithoven** [comment]
Loving those two commands. But if we're dreaming, it would be even better if we could somehow combine them, because usually you'd want to run both at the same time? Having them combined would make it easier to add it to a Makefile or npm start script.  
I'm no expert on bundling, but all it's config should be in config.js (after using `jspm bundle`), maybe `jspm serve` could also watch and auto bundle based on that config?

**Comment by capaj** [comment]
@guybedford what is the difference between `System.register()` and `System.registerDynamic()` I have just peeked into my bundle and it seems like I know less about JSPM than I thought...

**Comment by guybedford** [comment]
`System.register` is the ES module compatibility format, while `System.registerDynamic` is a wrapper format for AMD, CommonJS and global execution.

**Comment by alexisvincent** [comment]
`systemjs-hmr` supports this
